runtime: nodejs20
service: default

# Static file handlers - simple approach
handlers:
  # Serve main chatbot at root
  - url: /
    static_files: simple-chatbot.html
    upload: simple-chatbot.html
    secure: always

  # Serve admin panel
  - url: /admin-panel.html
    static_files: admin-panel.html
    upload: admin-panel.html
    secure: always

  # Serve other HTML files
  - url: /(.*\.html)
    static_files: \1
    upload: .*\.html
    secure: always

  # Serve static assets
  - url: /(.*\.(css|js|png|jpg|jpeg|gif|ico|svg|txt|md))
    static_files: \1
    upload: .*\.(css|js|png|jpg|jpeg|gif|ico|svg|txt|md)
    secure: always

# Environment variables
env_variables:
  NODE_ENV: production

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 5