runtime: nodejs20
service: default

# Use Node.js server for proper routing
handlers:
  - url: /.*
    script: auto
    secure: always

# Environment variables
env_variables:
  NODE_ENV: production

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 5