runtime: nodejs20
service: default

# Static file handlers for frontend
handlers:
  # Serve static files
  - url: /static
    static_dir: static
    secure: always

  # Serve main HTML files
  - url: /
    static_files: simple-chatbot.html
    upload: simple-chatbot.html
    secure: always

  - url: /admin
    static_files: admin-panel.html
    upload: admin-panel.html
    secure: always

  - url: /enhanced
    static_files: enhanced-chatbot.html
    upload: enhanced-chatbot.html
    secure: always

  # Serve all HTML files
  - url: /(.*\.html)
    static_files: \1
    upload: .*\.html
    secure: always

  # Serve CSS, JS, and other assets
  - url: /(.*\.(css|js|png|jpg|jpeg|gif|ico|svg))
    static_files: \1
    upload: .*\.(css|js|png|jpg|jpeg|gif|ico|svg)
    secure: always

  # Default handler
  - url: /.*
    static_files: simple-chatbot.html
    upload: simple-chatbot.html
    secure: always

# Environment variables
env_variables:
  NODE_ENV: production

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 5