runtime: nodejs20
service: api

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Network settings
network:
  forwarded_ports:
    - 8080

# Security settings
handlers:
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Health check
readiness_check:
  path: "/api/test"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/test"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Access to Google Cloud services
includes:
  - env_variables.yaml